language: python
python:
    - "3.4"
    - "3.5"
addons:
    - postgresql: '9.3'
services:
    - redis-server
install:
    - pip install -r requirements/development.txt
before_script:
    - psql -c 'CREATE DATABASE fastube;' -U postgres
    - make migrate
script:
    - pep8 .
    - python fastube/manage.py test users posts
notifications:
  slack: gruteogisu:zukA6UduCWPCpn0JaRnXm300
